// <auto-generated />
using System;
using Api_SistemaCursosDistancia.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_SistemaCursosDistancia.Migrations
{
    [DbContext(typeof(CursoDistanciaContext))]
    partial class CursoDistanciaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api_SistemaCursosDistancia.Models.AulaCD", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("ModuloCDid")
                        .HasColumnType("int");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("arquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("conteudo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("ModuloCDid");

                    b.ToTable("AulaCDs");
                });

            modelBuilder.Entity("Api_SistemaCursosDistancia.Models.CadastroCD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CadastroCDs");
                });

            modelBuilder.Entity("Api_SistemaCursosDistancia.Models.CursoCD", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("CadastroCDId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Instrutor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("dataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("CadastroCDId");

                    b.ToTable("CursoCDs");
                });

            modelBuilder.Entity("Api_SistemaCursosDistancia.Models.ModuloCD", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("CursoCDid")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("CursoCDid");

                    b.ToTable("ModuloCDs");
                });

            modelBuilder.Entity("Api_SistemaCursosDistancia.Models.AulaCD", b =>
                {
                    b.HasOne("Api_SistemaCursosDistancia.Models.ModuloCD", "ModuloCD")
                        .WithMany("aulaCDs")
                        .HasForeignKey("ModuloCDid");

                    b.Navigation("ModuloCD");
                });

            modelBuilder.Entity("Api_SistemaCursosDistancia.Models.CursoCD", b =>
                {
                    b.HasOne("Api_SistemaCursosDistancia.Models.CadastroCD", null)
                        .WithMany("CursoCDs")
                        .HasForeignKey("CadastroCDId");
                });

            modelBuilder.Entity("Api_SistemaCursosDistancia.Models.ModuloCD", b =>
                {
                    b.HasOne("Api_SistemaCursosDistancia.Models.CursoCD", "CursoCD")
                        .WithMany("ModuloCDs")
                        .HasForeignKey("CursoCDid");

                    b.Navigation("CursoCD");
                });

            modelBuilder.Entity("Api_SistemaCursosDistancia.Models.CadastroCD", b =>
                {
                    b.Navigation("CursoCDs");
                });

            modelBuilder.Entity("Api_SistemaCursosDistancia.Models.CursoCD", b =>
                {
                    b.Navigation("ModuloCDs");
                });

            modelBuilder.Entity("Api_SistemaCursosDistancia.Models.ModuloCD", b =>
                {
                    b.Navigation("aulaCDs");
                });
#pragma warning restore 612, 618
        }
    }
}
